version: '3.8'
services:
  db:
    container_name: partyup-startup-container
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=UTC
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3406:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --sql-mode="NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1 --log_bin_trust_function_creators=1 --skip-ssl
    healthcheck:
      test: "/usr/bin/mysql --user=${DB_USER} --password=${DB_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
  webserver:
    container_name: ms/web-application
    image: ms/web-application
    ports:
      - "8081:8080"
    environment:
      JAVA_OPTS:
        -DDB_HOSTNAME=${DB_HOSTNAME}
        -DDB_PORT=3406
        -DDB_DATABASE=${DB_NAME}
        -DDB_USER=${DB_USER}
        -DDB_PASSWORD=${DB_PASSWORD}
        -DGAME_LOOKUP_KEY=${GAME_LOOKUP_KEY}